"""Add company, point, and ranking models for seeding

Revision ID: 457e299777ee
Revises: 002_add_btob_features_tables
Create Date: 2025-08-20 09:11:57.816012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '457e299777ee'
down_revision = '002_add_btob_features_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_company_id'), 'points', ['company_id'], unique=False)
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_points_user_id'), 'points', ['user_id'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_company_id'), 'rankings', ['company_id'], unique=False)
    op.create_index(op.f('ix_rankings_id'), 'rankings', ['id'], unique=False)
    op.create_index(op.f('ix_rankings_user_id'), 'rankings', ['user_id'], unique=False)
    op.drop_table('report_items')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('period_start', sa.DATE(), nullable=False),
    sa.Column('period_end', sa.DATE(), nullable=False),
    sa.Column('methodology', mysql.ENUM('ghg_protocol', 'internal', 'other'), nullable=False),
    sa.Column('scope1_reduction_kg', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('scope2_reduction_kg', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('scope3_reduction_kg', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_reduction_kg', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('draft', 'published'), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('report_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('report_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('site_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('device_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('scope', mysql.ENUM('scope1', 'scope2', 'scope3'), nullable=False),
    sa.Column('amount_kg', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='report_items_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_rankings_user_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_company_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_points_user_id'), table_name='points')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_index(op.f('ix_points_company_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###