"""Add reports and report_items tables

Revision ID: e01b795f71f0
Revises: 001_initial_migration
Create Date: 2025-08-18 02:34:45.413099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01b795f71f0'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('company_id', sa.String(255), nullable=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('period_start', sa.Date(), nullable=False),
        sa.Column('period_end', sa.Date(), nullable=False),
        sa.Column('methodology', sa.Enum('ghg_protocol', 'internal', 'other', name='methodologyenum'), nullable=False),
        sa.Column('scope1_reduction_kg', sa.Numeric(15, 2), nullable=False),
        sa.Column('scope2_reduction_kg', sa.Numeric(15, 2), nullable=False),
        sa.Column('scope3_reduction_kg', sa.Numeric(15, 2), nullable=False),
        sa.Column('total_reduction_kg', sa.Numeric(15, 2), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('draft', 'published', name='statusenum'), nullable=False),
        sa.Column('created_by', sa.String(255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_items',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('report_id', sa.CHAR(36), nullable=False),
        sa.Column('site_name', sa.String(255), nullable=False),
        sa.Column('device_name', sa.String(255), nullable=False),
        sa.Column('scope', sa.Enum('scope1', 'scope2', 'scope3', name='scopeenum'), nullable=False),
        sa.Column('amount_kg', sa.Numeric(15, 2), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_items')
    op.drop_table('reports')
    # ### end Alembic commands ###